sudo: required

services: 
  -docker
  
language: java     

jdk:
  - oraclejdk8
#  - sudo docker-compose up

env:
  matrix:
    - TEST_CATEGORY=firefox
    - TEST_CATEGORY=chrome

matrix:
  fast_finish: true

before_script:
  - sudo docker-compose up -d

script:
  - if [ $TEST_CATEGORY == 'firefox' ]; then mvn test -P firefox; fi
  - if [ $TEST_CATEGORY == 'chrome' ]; then mvn test -P chrome; fi

after_success:
script:
  - git branch delivery
  - git push -f origin delivery



      
      
