sudo: required

services:
  -docker

language: java

jdk:
  - oraclejdk8

before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
- git lfs pull

branches:
  only:
    - master

jobs:
  include:
    - stage: Test
      env:
        - BROWSER=chrome
      script:
      - if [ $BROWSER == 'chrome' ]; then sudo docker-compose up -d; fi
      - if [ $BROWSER == 'chrome' ]; then mvn test -P chrome; fi
    - stage: Test
      env:
        - BROWSER=firefox
      script:
      - if [ $BROWSER == 'firefox' ]; then sudo docker-compose up -d; fi
      - if [ $BROWSER == 'firefox' ]; then mvn test -P firefox; fi
    - stage: deploy
      script:
      - git branch prod
      - git push -f origin prod