sudo: required

services: 
  -docker
  
language: java     

jdk:
  - oraclejdk8

env:

  DOCKER_COMPOSE_VERSION: 3.0

before_install:
  - sudo docker-compose up

env:
  matrix:
    - TEST_CATEGORY=firefox
    - TEST_CATEGORY=chrome

matrix:
  fast_finish: true

script:
  - if [ $TEST_CATEGORY == 'firefox' ]; then mvn test -P firefox; fi
  - if [ $TEST_CATEGORY == 'chrome' ]; then mvn test -P chrome; fi

after_success:
script:
  - sudo docker-compose down
      


      
      
