sudo: required

services: 
  -docker
  
language: java     

jdk:
  - oraclejdk8

before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
- git lfs pull

env:
  matrix:
    - TEST_CATEGORY=firefox
    - TEST_CATEGORY=chrome

branches:
  only:
    - master

matrix:
  fast_finish: true

before_script:
  - sudo docker-compose up -d

script:
  - if [ $TEST_CATEGORY == 'firefox' ]; then mvn test -P firefox; fi
  - if [ $TEST_CATEGORY == 'chrome' ]; then mvn test -P chrome; fi
  - if [ "x$TEST" = "0" ]; then git branch delivery; fi;
  - if [ "x$TEST" = "0" ]; then git push -f origin delivery; fi;
  #  - if [[ $BUILD == 0 ]]; then git branch delivery; fi
   # - if [[ $BUILD == 0 ]]; then git push -f origin delivery; fi;

after_success:
script:
  - if [[ $BUILD == 0 ]]; then git branch delivery; fi
  - if [[ $BUILD == 0 ]]; then git push -f origin delivery; fi;
  # if [ "x$TEST" = "x--enable-tests" ]; then cabal new-test -w ${HC} ${TEST} all; fi
 # - git branch delivery
  #- git push -f origin delivery



      
      
