language: java
dist: trusty
sudo: required
group: deprecated-2017Q4

jdk: openjdk8

services:
  - docker

before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
- git lfs pull

addons:
firefox: "44.0"

addons:
  apt:
    sources:
      - google-chrome
    packages:
- google-chrome-stable

branches:
  only:
    - master
    - release

stages:
  - Test
  - Push docker image
  - name: deploy prod
if: branch = master

jobs:
  include:
    - stage: Test
      os:
        - linux
      env:
        - BROWSER=chrome
      before_script:
      - "export DISPLAY=:99.0"
      - "sh -e /etc/init.d/xvfb start"
      - sleep 5 # give xvfb some time to start
      script:
      - if [ $BROWSER == 'chrome' ]; then docker-compose up --build -d; fi
      - if [ $BROWSER == 'chrome' ]; then mvn test -P linux-chrome -rf :selenium; fi
    - stage: Test
      os:
        - linux
      env:
        - BROWSER=firefox
      before_script:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 5 # give xvfb some time to start
      script:
       - if [ $BROWSER == 'firefox' ]; then docker-compose up --build -d; fi
       - if [ $BROWSER == 'firefox' ]; then mvn test -P linux-firefox -rf :selenium; fi
    - stage: Push docker image
      os:
        - linux
      env:
        - IMAGE=task/delivery
      script:
      - mvn clean package -DskipTests=true
      - mvn docker:build -rf :app
      - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - docker push ${IMAGE}
    - stage: deploy prod
      env:
        - BRANCH_PROD=prod
      script:
      - git branch ${BRANCH_PROD}
      - git push -f origin ${BRANCH_PROD}
