language: java
dist: trusty
sudo: required
group: deprecated-2017Q4

jdk: openjdk8

services:
  - docker

before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
- git lfs pull

branches:
  only:
    - master
    - release

stages:
  - Test
  - name: deploy prod
if: branch = master

jobs:
  include:
    - stage: Test
      os:
        - linux
      env:
        - BROWSER=chrome
      script:
  #    - java -jar -d ./app/target/app-1.jar
 #     - d java -jar ./app/target/app-1.jar
#      - mvn clean package -DskipTests=true -rf :app
      - java  -jar ./app/target/app-1.jar
      - if [ $BROWSER == 'chrome' ]; then docker-compose up -d; fi
      - if [ $BROWSER == 'chrome' ]; then mvn test -P linux-chrome -rf :selenium; fi
    - stage: Test
      os:
        - linux
      env:
        - BROWSER=firefox
      script:
       - ./release.sh
       - bash ./release.sh
       - bash release.sh
 #     - if [ $BROWSER == 'firefox' ]; then java -jar ./app/target/app-1.jar -d; fi
#      - javac -d ./app/src/main/java/com/tloureiro/SimpleCrmApplication.java
 #     - javac -d /app/src/main/java/com/tloureiro/SimpleCrmApplication.java
 #     - if [ $BROWSER == 'firefox' ]; then docker-compose up -d; fi
  #    - if [ $BROWSER == 'firefox' ]; then mvn test -P linux-firefox -rf :selenium; fi
      after_script:
      - if [ $BROWSER == 'firefox' ]; then docker-compose up -d; fi
      - if [ $BROWSER == 'firefox' ]; then mvn test -P linux-firefox -rf :selenium; fi

    - stage: deploy prod
      env:
        - BRANCH_PROD=prod
      script:
      - git branch ${BRANCH_PROD}
      - git push -f origin ${BRANCH_PROD}
