language: java
dist: trusty
sudo: required
group: deprecated-2017Q4

jdk: openjdk8

services:
  - docker

before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
- git lfs pull

branches:
  only:
    - master
    - release

stages:
  - Test
  - name: deploy prod
if: branch = master

jobs:
  include:
    - stage: Test
      os:
        - linux
      env:
        - BROWSER=chrome
      script:
      - mvn clean package -DskipTests=true
      - mvn docker:build -rf :app
      - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - docker push fiodar/td
      - if [ $BROWSER == 'chrome' ]; then docker run -it -p 8080:8080 -p 2000:2000 fiodar/td:lates -d; fi
      - if [ $BROWSER == 'chrome' ]; then docker-compose up -d; fi
      - if [ $BROWSER == 'chrome' ]; then mvn test -P linux-chrome -rf :selenium; fi
    - stage: Test
      os:
        - linux
      env:
        - BROWSER=firefox
      script:
       - mvn clean package -DskipTests=true
       - mvn docker:build -rf :app
       - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
       - docker push fiodar/td
       - docker run -d -it -p 8080:8080 -p 2000:2000 fiodar/td:lates
       - if [ $BROWSER == 'firefox' ]; then docker-compose up -d; fi
       - if [ $BROWSER == 'firefox' ]; then mvn test -P linux-firefox -rf :selenium; fi
    - stage: deploy prod
      env:
        - BRANCH_PROD=prod
      script:
      - git branch ${BRANCH_PROD}
      - git push -f origin ${BRANCH_PROD}
