sudo: required

services: 
  -docker
  
language: java     

dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

addons:
   firefox: "57.0"

jdk:
  - oraclejdk8

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024"
  - sleep 3

env:

  DOCKER_COMPOSE_VERSION: 3.0

env:
  matrix:
    - TEST_CATEGORY=firefox
    - TEST_CATEGORY=chrome

matrix:
  fast_finish: true

before_script:
  # Selenium server
  - "wget http://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-3.7.1.jar" -
  - "wget %url_of_your_lib% # download your framework or framework dependencies (selenium libs, etc.)
  - "java -jar selenium-server-standalone-3.7.1.jar > /dev/null 2>/dev/null &"
  - sleep 20 # gives enough time to Selenium to start

script:
  - if [ $TEST_CATEGORY == 'firefox' ]; then mvn test -P firefox; fi
  - if [ $TEST_CATEGORY == 'chrome' ]; then mvn test -P chrome; fi

#after_success:
#script:
 # - sudo docker-compose down


      
      
