sudo: required

services:
  -docker

language: java

jdk:
  - oraclejdk8

before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
- git lfs pull

branches:
  only:
    - master

stages:
  - Test
  - deploy test
  - name: deploy
if: branch = master

jobs:
  include:
    - stage: Test
      os:
        - osx
      env:
        - BROWSER=chrome
      script:
      - if [ $BROWSER == 'chrome' ]; then sudo docker-compose up -d; fi
      - if [ $BROWSER == 'chrome' ]; then mvn test -P chrome; fi
    - stage: Test
      os:
        - osx
      env:
        - BROWSER=firefox
      script:
      - if [ $BROWSER == 'firefox' ]; then sudo docker-compose up -d; fi
      - if [ $BROWSER == 'firefox' ]; then mvn test -P firefox; fi
    - stage: Test
      os:
        - linux
      env:
        - BROWSER=chrome
      script:
      - if [ $BROWSER == 'chrome' ]; then sudo docker-compose up -d; fi
      - if [ $BROWSER == 'chrome' ]; then mvn test -P chrome; fi
    - stage: Test
      os:
        - linux
      env:
        - BROWSER=firefox
      script:
      - if [ $BROWSER == 'firefox' ]; then sudo docker-compose up -d; fi
      - if [ $BROWSER == 'firefox' ]; then mvn test -P firefox; fi
    - stage: deploy
      env:
        - BRANCH_PROD=prod
      script:
      - git branch ${BRANCH_PROD}
      - git push -f origin ${BRANCH_PROD}         
    - stage: deploy test
      env:
        - BRANCH_LINUX_FIREFOX=linux-firefox
      script:
      - git branch ${BRANCH_LINUX_FIREFOX}
      - git push -f origin ${BRANCH_LINUX_FIREFOX}
    - stage: deploy test
      env:
        - BRANCH_LINUX_CHROME=prod
      script:
      - git branch ${BRANCH_LINUX_CHROME}
      - git push -f origin ${BRANCH_LINUX_CHROME}
    - stage: deploy test
      env:
        - BRANCH_OSX_CHROME=prod
      script:
      - git branch ${BRANCH_OSX_CHROME}
      - git push -f origin ${BRANCH_OSX_CHROME}
    - stage: deploy test
      env:
        - BRANCH_OSX_FIREFOX=prod
      script:
      - git branch ${BRANCH_OSX_FIREFOX}
      - git push -f origin ${BRANCH_OSX_FIREFOX}
