version: "2"
services:
   app:
     build:
         context: .
         dockerfile: Dockerfile.build
     volumes:
         - "$HOME/.m2:/root/.m2"
     ports:
         - "7070:7070"
     command: mvn spring-boot:run